apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l5s4ugbi6-java-springboot
  janus-idp.io/tekton: l5s4ugbi6-java-springboot
  backstage.io/kubernetes-id: l5s4ugbi6-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l5s4ugbi6-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
